# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b0b6955127bdf160a5ee2110563db97435dd72e3531e5c21a824f4da8f901ef708758c1512e33075e6854f9bbfdae0dd2ef3576b9771814b07a72d04f5d784

test:
  secret_key_base: 63779ea6e0ba81ff1844affd9ab092958f91b4f96358ae1af661a3315a183654819659aca99aaed2b299b2b042f1045f9760608b8b68ae89750ee6630359f345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
